//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chloe.Client.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchCriteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchCriteria()
        {
            this.Chloe = new HashSet<Flight>();
        }
    
        public int Id { get; set; }
        public int CityFrom_Id { get; set; }
        public int CityTo_Id { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int FlightWebsite_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public int ReceiverGroups_Id { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Chloe { get; set; }
        public virtual FlightWebsite FlightWebsite { get; set; }
        public virtual ReceiverGroup ReceiverGroup { get; set; }
    }
}
