//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flights.Domain.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchCriterias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchCriterias()
        {
            this.Flights = new HashSet<Flights>();
        }
    
        public int Id { get; set; }
        public int CityFrom_Id { get; set; }
        public int CityTo_Id { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int Carrier_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Cities CityFrom { get; set; }
        public virtual Cities CityTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flights> Flights { get; set; }
        public virtual Carriers Carriers { get; set; }
    }
}
