//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flights.Domain.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchCriteria_View
    {
        public int Id { get; set; }
        public System.DateTime DataWylotu { get; set; }
        public string Nazwa { get; set; }
        public string Do { get; set; }
        public string Od { get; set; }
        public string Strona { get; set; }
    }
}
