//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flights.Domain.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationReceiversGroups
    {
        public int Id { get; set; }
        public int ReceiverGroups_Id { get; set; }
        public int NotificationReceivers_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual NotificationReceivers NotificationReceivers { get; set; }
        public virtual ReceiverGroups ReceiverGroups { get; set; }
    }
}
