//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flights.Client.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchCriteria_View
    {
        public System.DateTime Data_wylotu { get; set; }
        public string Nazwa { get; set; }
        public string Do { get; set; }
        public string Od { get; set; }
        public string Przewoźnik { get; set; }
    }
}
